# Generated by Django 5.2.8 on 2026-04-15 11:08

import django.db.models.deletion
import skin_journal.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='JournalEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('mood', models.CharField(blank=True, choices=[('great', '😄 Great'), ('good', '🙂 Good'), ('neutral', '😐 Neutral'), ('bad', '😕 Bad'), ('terrible', '😞 Terrible')], max_length=20)),
                ('skin_condition', models.CharField(blank=True, choices=[('clear', '✨ Clear'), ('oily', '💧 Oily'), ('dry', '🌵 Dry'), ('breakout', '🔴 Breakout'), ('sensitive', '🌸 Sensitive'), ('combination', '🔀 Combination')], max_length=20)),
                ('notes', models.TextField(blank=True)),
                ('products_used', models.TextField(blank=True, help_text='Comma-separated product names')),
                ('image', models.ImageField(blank=True, null=True, upload_to=skin_journal.models.journal_image_path)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='journal_entries', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-date', '-created_at'],
                'unique_together': {('user', 'date')},
            },
        ),
    ]
