# Generated by Django 5.2.8 on 2026-04-15 11:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('skin_journal', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='journalentry',
            name='acne_severity',
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='journalentry',
            name='dark_spots_severity',
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='journalentry',
            name='wrinkles_severity',
            field=models.PositiveSmallIntegerField(default=0),
        ),
    ]
