# Generated by Django 5.2.8 on 2026-04-15 12:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('skin_journal', '0002_journalentry_acne_severity_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='journalentry',
            name='mood',
        ),
    ]
