# Generated by Django 5.2.8 on 2025-12-13 05:43

import django.core.validators
import face_analysis.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CNNModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text="Name for this model (e.g., 'MobileNet Skin Types v1')", max_length=200)),
                ('model_type', models.CharField(choices=[('skin_types', 'Skin Types'), ('skin_concerns', 'Skin Concerns')], help_text='Type of model: skin types or skin concerns', max_length=20)),
                ('model_file', models.FileField(help_text='Upload trained model file (.h5, .keras, or .pb format)', upload_to=face_analysis.models.model_file_upload_path, validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['h5', 'keras', 'pb'])])),
                ('training_data_file', models.FileField(blank=True, help_text='Upload training data JSON file (class names, history, etc.)', null=True, upload_to=face_analysis.models.training_data_upload_path, validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['json'])])),
                ('class_names_file', models.FileField(blank=True, help_text='Upload class names JSON file', null=True, upload_to=face_analysis.models.training_data_upload_path, validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['json'])])),
                ('description', models.TextField(blank=True, help_text='Optional description of the model')),
                ('version', models.CharField(default='1.0', help_text='Model version', max_length=50)),
                ('accuracy', models.DecimalField(blank=True, decimal_places=4, help_text='Model accuracy (0-1)', max_digits=5, null=True)),
                ('base_architecture', models.CharField(blank=True, help_text='Base architecture (e.g., MobileNetV2, ResNet50)', max_length=100)),
                ('image_size', models.CharField(default='224x224', help_text="Input image size (e.g., '224x224')", max_length=20)),
                ('is_active', models.BooleanField(default=False, help_text='Set as active model for this type (only one active per type)')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'CNN Model',
                'verbose_name_plural': 'CNN Models',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['model_type', 'is_active'], name='face_analys_model_t_e312a2_idx')],
            },
        ),
    ]
