# Generated by Django 5.2.8 on 2025-12-11 05:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Ingredient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=300, unique=True)),
                ('function', models.CharField(blank=True, max_length=200, null=True)),
                ('label', models.CharField(blank=True, max_length=100, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('brand', models.CharField(blank=True, max_length=200)),
                ('name', models.CharField(max_length=500)),
                ('category', models.CharField(blank=True, max_length=200)),
                ('inci_decoder_url', models.URLField(db_index=True, unique=True)),
                ('ingredients_json', models.JSONField(blank=True, default=list, help_text='List of ingredient dicts')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['brand', 'name'],
                'indexes': [models.Index(fields=['brand'], name='recommendat_brand_9ca7b4_idx'), models.Index(fields=['category'], name='recommendat_categor_157c7f_idx')],
            },
        ),
    ]
