# Generated by Django 5.2.8 on 2025-12-13 04:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recommendations', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='product',
            name='how_to_use',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='product',
            name='image_url',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='product_id',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='product_url',
            field=models.URLField(blank=True, db_index=True, help_text='Original product URL', null=True, unique=True),
        ),
        migrations.AddField(
            model_name='product',
            name='rating',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=3, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='review_count',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='product',
            name='size',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='product',
            name='skin_concerns',
            field=models.JSONField(blank=True, default=list, help_text='List of skin concerns addressed'),
        ),
        migrations.AddField(
            model_name='product',
            name='skin_types',
            field=models.JSONField(blank=True, default=list, help_text='List of suitable skin types'),
        ),
        migrations.AlterField(
            model_name='product',
            name='inci_decoder_url',
            field=models.URLField(blank=True, db_index=True, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='ingredients_json',
            field=models.JSONField(blank=True, default=list, help_text='List of ingredient dicts or list of ingredient names'),
        ),
    ]
